export const DonationTrancheABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_authority', type: 'address' },
      { name: '_usdt', type: 'address' },
      { name: '_clusterManager', type: 'address' },
      { name: '_vault', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  // Constants
  {
    type: 'function',
    name: 'TRANCHE_DURATION',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_TRANCHE_CAP',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_DEPOSIT',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DUST_THRESHOLD',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // State
  {
    type: 'function',
    name: 'usdt',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'clusterManager',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultAprBps',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentTrancheId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'scheduledTrancheCount',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getScheduledTranches',
    inputs: [],
    outputs: [
      { name: 'startTimes', type: 'uint256[]' },
      { name: 'endTimes', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'firstTrancheStarted',
    inputs: [],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  // View functions
  {
    type: 'function',
    name: 'getCurrentTranche',
    inputs: [],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'cap', type: 'uint256' },
      { name: 'totalDeposited', type: 'uint256' },
      { name: 'remaining', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
      { name: 'collected', type: 'bool' },
      { name: 'totalMatched', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTranche',
    inputs: [{ name: 'trancheId', type: 'uint256' }],
    outputs: [
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'cap', type: 'uint256' },
      { name: 'totalDeposited', type: 'uint256' },
      { name: 'collected', type: 'bool' },
      { name: 'totalMatched', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRemainingCapacity',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getEffectiveMinDeposit',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getExpectedMatch',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [
      { name: 'matchAmount', type: 'uint256' },
      { name: 'matchPercentBps', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNoteInfo',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'trancheId', type: 'uint256' },
      { name: 'aprBps', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'interestOwed', type: 'uint256' },
      { name: 'interestPerSecond', type: 'uint256' },
      { name: 'principal', type: 'uint256' },
      { name: 'principalRepaid', type: 'uint256' },
      { name: 'interestPaid', type: 'uint256' },
      { name: 'interestAccrued', type: 'uint256' },
      { name: 'remainingPrincipal', type: 'uint256' },
      { name: 'totalRepaid', type: 'uint256' },
      { name: 'fullyRepaid', type: 'bool' },
      { name: 'completedTimestamp', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  // Write functions
  {
    type: 'function',
    name: 'deposit',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [{ name: 'tokenId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      { name: 'tokenId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collectTranche',
    inputs: [{ name: 'trancheId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Admin functions
  {
    type: 'function',
    name: 'startFirstTranche',
    inputs: [{ name: 'startTimestamp', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'startNextTranche',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'scheduleAdditionalTranches',
    inputs: [
      { name: 'count', type: 'uint256' },
      { name: 'startOverride', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVault',
    inputs: [{ name: 'newVault', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDefaultApr',
    inputs: [{ name: 'newAprBps', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'authority',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  // ERC721
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  // ERC721Enumerable
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenByIndex',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenOfOwnerByIndex',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // Events
  {
    type: 'event',
    name: 'TrancheStarted',
    inputs: [
      { name: 'trancheId', type: 'uint256', indexed: true },
      { name: 'startTime', type: 'uint256', indexed: false },
      { name: 'endTime', type: 'uint256', indexed: false },
      { name: 'cap', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Deposited',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'depositor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'trancheId', type: 'uint256', indexed: false },
      { name: 'matched', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Repaid',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'payer', type: 'address', indexed: true },
      { name: 'interestPaid', type: 'uint256', indexed: false },
      { name: 'principalPaid', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NoteCompleted',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'totalPrincipalRepaid', type: 'uint256', indexed: false },
      { name: 'totalInterestPaid', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'TrancheCollected',
    inputs: [
      { name: 'trancheId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  // Errors
  {
    type: 'error',
    name: 'TrancheNotActive',
    inputs: [],
  },
  {
    type: 'error',
    name: 'BelowMinimumDeposit',
    inputs: [],
  },
  {
    type: 'error',
    name: 'TrancheFull',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NoteFullyRepaid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidNote',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ZeroAmount',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidStartTime',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NoTranchesScheduled',
    inputs: [],
  },
  {
    type: 'error',
    name: 'FirstTrancheAlreadyStarted',
    inputs: [],
  },
] as const;
